// Code generated by MockGen. DO NOT EDIT.
// Source: todoService.go
//
// Generated by this command:
//
//	mockgen -source=todoService.go -destination=mock/todoService.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	model "server/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MocktodoRepository is a mock of todoRepository interface.
type MocktodoRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktodoRepositoryMockRecorder
	isgomock struct{}
}

// MocktodoRepositoryMockRecorder is the mock recorder for MocktodoRepository.
type MocktodoRepositoryMockRecorder struct {
	mock *MocktodoRepository
}

// NewMocktodoRepository creates a new mock instance.
func NewMocktodoRepository(ctrl *gomock.Controller) *MocktodoRepository {
	mock := &MocktodoRepository{ctrl: ctrl}
	mock.recorder = &MocktodoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktodoRepository) EXPECT() *MocktodoRepositoryMockRecorder {
	return m.recorder
}

// CreateItem mocks base method.
func (m *MocktodoRepository) CreateItem(item model.Identifier) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateItem", item)
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MocktodoRepositoryMockRecorder) CreateItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MocktodoRepository)(nil).CreateItem), item)
}

// DeleteHomeworkItem mocks base method.
func (m *MocktodoRepository) DeleteHomeworkItem(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHomeworkItem", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHomeworkItem indicates an expected call of DeleteHomeworkItem.
func (mr *MocktodoRepositoryMockRecorder) DeleteHomeworkItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHomeworkItem", reflect.TypeOf((*MocktodoRepository)(nil).DeleteHomeworkItem), id)
}

// DeleteStudyItem mocks base method.
func (m *MocktodoRepository) DeleteStudyItem(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudyItem", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudyItem indicates an expected call of DeleteStudyItem.
func (mr *MocktodoRepositoryMockRecorder) DeleteStudyItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudyItem", reflect.TypeOf((*MocktodoRepository)(nil).DeleteStudyItem), id)
}

// DeleteWorkoutItem mocks base method.
func (m *MocktodoRepository) DeleteWorkoutItem(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkoutItem", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkoutItem indicates an expected call of DeleteWorkoutItem.
func (mr *MocktodoRepositoryMockRecorder) DeleteWorkoutItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkoutItem", reflect.TypeOf((*MocktodoRepository)(nil).DeleteWorkoutItem), id)
}

// GetHomeworkItem mocks base method.
func (m *MocktodoRepository) GetHomeworkItem(id int) (*model.HomeworkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHomeworkItem", id)
	ret0, _ := ret[0].(*model.HomeworkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHomeworkItem indicates an expected call of GetHomeworkItem.
func (mr *MocktodoRepositoryMockRecorder) GetHomeworkItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHomeworkItem", reflect.TypeOf((*MocktodoRepository)(nil).GetHomeworkItem), id)
}

// GetHomeworkItems mocks base method.
func (m *MocktodoRepository) GetHomeworkItems() ([]*model.HomeworkItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHomeworkItems")
	ret0, _ := ret[0].([]*model.HomeworkItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHomeworkItems indicates an expected call of GetHomeworkItems.
func (mr *MocktodoRepositoryMockRecorder) GetHomeworkItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHomeworkItems", reflect.TypeOf((*MocktodoRepository)(nil).GetHomeworkItems))
}

// GetLastStudyItemId mocks base method.
func (m *MocktodoRepository) GetLastStudyItemId() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastStudyItemId")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLastStudyItemId indicates an expected call of GetLastStudyItemId.
func (mr *MocktodoRepositoryMockRecorder) GetLastStudyItemId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastStudyItemId", reflect.TypeOf((*MocktodoRepository)(nil).GetLastStudyItemId))
}

// GetLastWorkoutItemId mocks base method.
func (m *MocktodoRepository) GetLastWorkoutItemId() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastWorkoutItemId")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLastWorkoutItemId indicates an expected call of GetLastWorkoutItemId.
func (mr *MocktodoRepositoryMockRecorder) GetLastWorkoutItemId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastWorkoutItemId", reflect.TypeOf((*MocktodoRepository)(nil).GetLastWorkoutItemId))
}

// GetLasttHomeworkItemId mocks base method.
func (m *MocktodoRepository) GetLasttHomeworkItemId() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLasttHomeworkItemId")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetLasttHomeworkItemId indicates an expected call of GetLasttHomeworkItemId.
func (mr *MocktodoRepositoryMockRecorder) GetLasttHomeworkItemId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLasttHomeworkItemId", reflect.TypeOf((*MocktodoRepository)(nil).GetLasttHomeworkItemId))
}

// GetNewHomewors mocks base method.
func (m *MocktodoRepository) GetNewHomewors(lastHomeworkItemId int) (int, []*model.HomeworkItem) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewHomewors", lastHomeworkItemId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]*model.HomeworkItem)
	return ret0, ret1
}

// GetNewHomewors indicates an expected call of GetNewHomewors.
func (mr *MocktodoRepositoryMockRecorder) GetNewHomewors(lastHomeworkItemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewHomewors", reflect.TypeOf((*MocktodoRepository)(nil).GetNewHomewors), lastHomeworkItemId)
}

// GetNewStudies mocks base method.
func (m *MocktodoRepository) GetNewStudies(lastStudyItemId int) (int, []*model.StudyItem) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewStudies", lastStudyItemId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]*model.StudyItem)
	return ret0, ret1
}

// GetNewStudies indicates an expected call of GetNewStudies.
func (mr *MocktodoRepositoryMockRecorder) GetNewStudies(lastStudyItemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewStudies", reflect.TypeOf((*MocktodoRepository)(nil).GetNewStudies), lastStudyItemId)
}

// GetNewWorkouts mocks base method.
func (m *MocktodoRepository) GetNewWorkouts(lastWorkoutItemId int) (int, []*model.WorkoutItem) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNewWorkouts", lastWorkoutItemId)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]*model.WorkoutItem)
	return ret0, ret1
}

// GetNewWorkouts indicates an expected call of GetNewWorkouts.
func (mr *MocktodoRepositoryMockRecorder) GetNewWorkouts(lastWorkoutItemId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNewWorkouts", reflect.TypeOf((*MocktodoRepository)(nil).GetNewWorkouts), lastWorkoutItemId)
}

// GetStudyItem mocks base method.
func (m *MocktodoRepository) GetStudyItem(id int) (*model.StudyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyItem", id)
	ret0, _ := ret[0].(*model.StudyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyItem indicates an expected call of GetStudyItem.
func (mr *MocktodoRepositoryMockRecorder) GetStudyItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyItem", reflect.TypeOf((*MocktodoRepository)(nil).GetStudyItem), id)
}

// GetStudyItems mocks base method.
func (m *MocktodoRepository) GetStudyItems() ([]*model.StudyItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudyItems")
	ret0, _ := ret[0].([]*model.StudyItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudyItems indicates an expected call of GetStudyItems.
func (mr *MocktodoRepositoryMockRecorder) GetStudyItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudyItems", reflect.TypeOf((*MocktodoRepository)(nil).GetStudyItems))
}

// GetWorkoutItem mocks base method.
func (m *MocktodoRepository) GetWorkoutItem(id int) (*model.WorkoutItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkoutItem", id)
	ret0, _ := ret[0].(*model.WorkoutItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkoutItem indicates an expected call of GetWorkoutItem.
func (mr *MocktodoRepositoryMockRecorder) GetWorkoutItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkoutItem", reflect.TypeOf((*MocktodoRepository)(nil).GetWorkoutItem), id)
}

// GetWorkoutItems mocks base method.
func (m *MocktodoRepository) GetWorkoutItems() ([]*model.WorkoutItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkoutItems")
	ret0, _ := ret[0].([]*model.WorkoutItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkoutItems indicates an expected call of GetWorkoutItems.
func (mr *MocktodoRepositoryMockRecorder) GetWorkoutItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkoutItems", reflect.TypeOf((*MocktodoRepository)(nil).GetWorkoutItems))
}

// UpdateItem mocks base method.
func (m *MocktodoRepository) UpdateItem(item model.Identifier) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateItem", item)
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MocktodoRepositoryMockRecorder) UpdateItem(item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MocktodoRepository)(nil).UpdateItem), item)
}
