// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: grpc/v1/homework.proto

package todo_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateHomeworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomeworkRequest) Reset() {
	*x = CreateHomeworkRequest{}
	mi := &file_grpc_v1_homework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomeworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomeworkRequest) ProtoMessage() {}

func (x *CreateHomeworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomeworkRequest.ProtoReflect.Descriptor instead.
func (*CreateHomeworkRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{0}
}

func (x *CreateHomeworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateHomeworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHomeworkRequest) Reset() {
	*x = UpdateHomeworkRequest{}
	mi := &file_grpc_v1_homework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomeworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomeworkRequest) ProtoMessage() {}

func (x *UpdateHomeworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomeworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateHomeworkRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateHomeworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHomeworkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetHomeworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeworkRequest) Reset() {
	*x = GetHomeworkRequest{}
	mi := &file_grpc_v1_homework_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeworkRequest) ProtoMessage() {}

func (x *GetHomeworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeworkRequest.ProtoReflect.Descriptor instead.
func (*GetHomeworkRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{2}
}

func (x *GetHomeworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHomeworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHomeworkResponse) Reset() {
	*x = GetHomeworkResponse{}
	mi := &file_grpc_v1_homework_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHomeworkResponse) ProtoMessage() {}

func (x *GetHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHomeworkResponse.ProtoReflect.Descriptor instead.
func (*GetHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{3}
}

func (x *GetHomeworkResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetHomeworkResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListHomeworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*GetHomeworkResponse `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHomeworkResponse) Reset() {
	*x = ListHomeworkResponse{}
	mi := &file_grpc_v1_homework_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeworkResponse) ProtoMessage() {}

func (x *ListHomeworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeworkResponse.ProtoReflect.Descriptor instead.
func (*ListHomeworkResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{4}
}

func (x *ListHomeworkResponse) GetResult() []*GetHomeworkResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteHomeworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHomeworkRequest) Reset() {
	*x = DeleteHomeworkRequest{}
	mi := &file_grpc_v1_homework_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHomeworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHomeworkRequest) ProtoMessage() {}

func (x *DeleteHomeworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_homework_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHomeworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteHomeworkRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_homework_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteHomeworkRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_grpc_v1_homework_proto protoreflect.FileDescriptor

const file_grpc_v1_homework_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/v1/homework.proto\x12\n" +
	"todoapi.v1\x1a\x1bgoogle/protobuf/empty.proto\"9\n" +
	"\x15CreateHomeworkRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"I\n" +
	"\x15UpdateHomeworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"$\n" +
	"\x12GetHomeworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x13GetHomeworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"O\n" +
	"\x14ListHomeworkResponse\x127\n" +
	"\x06result\x18\x01 \x03(\v2\x1f.todoapi.v1.GetHomeworkResponseR\x06result\"'\n" +
	"\x15DeleteHomeworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\x92\x03\n" +
	"\x0fHomeworkService\x12K\n" +
	"\x0eCreateHomework\x12!.todoapi.v1.CreateHomeworkRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0eUpdateHomework\x12!.todoapi.v1.UpdateHomeworkRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\vGetHomework\x12\x1e.todoapi.v1.GetHomeworkRequest\x1a\x1f.todoapi.v1.GetHomeworkResponse\x12H\n" +
	"\fListHomework\x12\x16.google.protobuf.Empty\x1a .todoapi.v1.ListHomeworkResponse\x12K\n" +
	"\x0eDeleteHomework\x12!.todoapi.v1.DeleteHomeworkRequest\x1a\x16.google.protobuf.EmptyB\x16Z\x14pkg/grpc/v1/todo_apib\x06proto3"

var (
	file_grpc_v1_homework_proto_rawDescOnce sync.Once
	file_grpc_v1_homework_proto_rawDescData []byte
)

func file_grpc_v1_homework_proto_rawDescGZIP() []byte {
	file_grpc_v1_homework_proto_rawDescOnce.Do(func() {
		file_grpc_v1_homework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_v1_homework_proto_rawDesc), len(file_grpc_v1_homework_proto_rawDesc)))
	})
	return file_grpc_v1_homework_proto_rawDescData
}

var file_grpc_v1_homework_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_v1_homework_proto_goTypes = []any{
	(*CreateHomeworkRequest)(nil), // 0: todoapi.v1.CreateHomeworkRequest
	(*UpdateHomeworkRequest)(nil), // 1: todoapi.v1.UpdateHomeworkRequest
	(*GetHomeworkRequest)(nil),    // 2: todoapi.v1.GetHomeworkRequest
	(*GetHomeworkResponse)(nil),   // 3: todoapi.v1.GetHomeworkResponse
	(*ListHomeworkResponse)(nil),  // 4: todoapi.v1.ListHomeworkResponse
	(*DeleteHomeworkRequest)(nil), // 5: todoapi.v1.DeleteHomeworkRequest
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_grpc_v1_homework_proto_depIdxs = []int32{
	3, // 0: todoapi.v1.ListHomeworkResponse.result:type_name -> todoapi.v1.GetHomeworkResponse
	0, // 1: todoapi.v1.HomeworkService.CreateHomework:input_type -> todoapi.v1.CreateHomeworkRequest
	1, // 2: todoapi.v1.HomeworkService.UpdateHomework:input_type -> todoapi.v1.UpdateHomeworkRequest
	2, // 3: todoapi.v1.HomeworkService.GetHomework:input_type -> todoapi.v1.GetHomeworkRequest
	6, // 4: todoapi.v1.HomeworkService.ListHomework:input_type -> google.protobuf.Empty
	5, // 5: todoapi.v1.HomeworkService.DeleteHomework:input_type -> todoapi.v1.DeleteHomeworkRequest
	6, // 6: todoapi.v1.HomeworkService.CreateHomework:output_type -> google.protobuf.Empty
	6, // 7: todoapi.v1.HomeworkService.UpdateHomework:output_type -> google.protobuf.Empty
	3, // 8: todoapi.v1.HomeworkService.GetHomework:output_type -> todoapi.v1.GetHomeworkResponse
	4, // 9: todoapi.v1.HomeworkService.ListHomework:output_type -> todoapi.v1.ListHomeworkResponse
	6, // 10: todoapi.v1.HomeworkService.DeleteHomework:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_v1_homework_proto_init() }
func file_grpc_v1_homework_proto_init() {
	if File_grpc_v1_homework_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_v1_homework_proto_rawDesc), len(file_grpc_v1_homework_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_homework_proto_goTypes,
		DependencyIndexes: file_grpc_v1_homework_proto_depIdxs,
		MessageInfos:      file_grpc_v1_homework_proto_msgTypes,
	}.Build()
	File_grpc_v1_homework_proto = out.File
	file_grpc_v1_homework_proto_goTypes = nil
	file_grpc_v1_homework_proto_depIdxs = nil
}
