// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: grpc/v1/homework.proto

package todo_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HomeworkService_CreateHomework_FullMethodName = "/todoapi.v1.HomeworkService/CreateHomework"
	HomeworkService_UpdateHomework_FullMethodName = "/todoapi.v1.HomeworkService/UpdateHomework"
	HomeworkService_GetHomework_FullMethodName    = "/todoapi.v1.HomeworkService/GetHomework"
	HomeworkService_ListHomework_FullMethodName   = "/todoapi.v1.HomeworkService/ListHomework"
	HomeworkService_DeleteHomework_FullMethodName = "/todoapi.v1.HomeworkService/DeleteHomework"
)

// HomeworkServiceClient is the client API for HomeworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HomeworkServiceClient interface {
	CreateHomework(ctx context.Context, in *CreateHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateHomework(ctx context.Context, in *UpdateHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetHomework(ctx context.Context, in *GetHomeworkRequest, opts ...grpc.CallOption) (*GetHomeworkResponse, error)
	ListHomework(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListHomeworkResponse, error)
	DeleteHomework(ctx context.Context, in *DeleteHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type homeworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomeworkServiceClient(cc grpc.ClientConnInterface) HomeworkServiceClient {
	return &homeworkServiceClient{cc}
}

func (c *homeworkServiceClient) CreateHomework(ctx context.Context, in *CreateHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HomeworkService_CreateHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeworkServiceClient) UpdateHomework(ctx context.Context, in *UpdateHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HomeworkService_UpdateHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeworkServiceClient) GetHomework(ctx context.Context, in *GetHomeworkRequest, opts ...grpc.CallOption) (*GetHomeworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHomeworkResponse)
	err := c.cc.Invoke(ctx, HomeworkService_GetHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeworkServiceClient) ListHomework(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListHomeworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHomeworkResponse)
	err := c.cc.Invoke(ctx, HomeworkService_ListHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homeworkServiceClient) DeleteHomework(ctx context.Context, in *DeleteHomeworkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HomeworkService_DeleteHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeworkServiceServer is the server API for HomeworkService service.
// All implementations must embed UnimplementedHomeworkServiceServer
// for forward compatibility.
type HomeworkServiceServer interface {
	CreateHomework(context.Context, *CreateHomeworkRequest) (*emptypb.Empty, error)
	UpdateHomework(context.Context, *UpdateHomeworkRequest) (*emptypb.Empty, error)
	GetHomework(context.Context, *GetHomeworkRequest) (*GetHomeworkResponse, error)
	ListHomework(context.Context, *emptypb.Empty) (*ListHomeworkResponse, error)
	DeleteHomework(context.Context, *DeleteHomeworkRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedHomeworkServiceServer()
}

// UnimplementedHomeworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomeworkServiceServer struct{}

func (UnimplementedHomeworkServiceServer) CreateHomework(context.Context, *CreateHomeworkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) UpdateHomework(context.Context, *UpdateHomeworkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) GetHomework(context.Context, *GetHomeworkRequest) (*GetHomeworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) ListHomework(context.Context, *emptypb.Empty) (*ListHomeworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) DeleteHomework(context.Context, *DeleteHomeworkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) mustEmbedUnimplementedHomeworkServiceServer() {}
func (UnimplementedHomeworkServiceServer) testEmbeddedByValue()                         {}

// UnsafeHomeworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomeworkServiceServer will
// result in compilation errors.
type UnsafeHomeworkServiceServer interface {
	mustEmbedUnimplementedHomeworkServiceServer()
}

func RegisterHomeworkServiceServer(s grpc.ServiceRegistrar, srv HomeworkServiceServer) {
	// If the following call pancis, it indicates UnimplementedHomeworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HomeworkService_ServiceDesc, srv)
}

func _HomeworkService_CreateHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).CreateHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_CreateHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).CreateHomework(ctx, req.(*CreateHomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeworkService_UpdateHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).UpdateHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_UpdateHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).UpdateHomework(ctx, req.(*UpdateHomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeworkService_GetHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).GetHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_GetHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).GetHomework(ctx, req.(*GetHomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeworkService_ListHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).ListHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_ListHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).ListHomework(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomeworkService_DeleteHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).DeleteHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_DeleteHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).DeleteHomework(ctx, req.(*DeleteHomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HomeworkService_ServiceDesc is the grpc.ServiceDesc for HomeworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomeworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todoapi.v1.HomeworkService",
	HandlerType: (*HomeworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHomework",
			Handler:    _HomeworkService_CreateHomework_Handler,
		},
		{
			MethodName: "UpdateHomework",
			Handler:    _HomeworkService_UpdateHomework_Handler,
		},
		{
			MethodName: "GetHomework",
			Handler:    _HomeworkService_GetHomework_Handler,
		},
		{
			MethodName: "ListHomework",
			Handler:    _HomeworkService_ListHomework_Handler,
		},
		{
			MethodName: "DeleteHomework",
			Handler:    _HomeworkService_DeleteHomework_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/v1/homework.proto",
}
