// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: grpc/v1/study.proto

package todo_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudyRequest) Reset() {
	*x = CreateStudyRequest{}
	mi := &file_grpc_v1_study_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudyRequest) ProtoMessage() {}

func (x *CreateStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudyRequest.ProtoReflect.Descriptor instead.
func (*CreateStudyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStudyRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UpdateStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudyRequest) Reset() {
	*x = UpdateStudyRequest{}
	mi := &file_grpc_v1_study_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyRequest) ProtoMessage() {}

func (x *UpdateStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStudyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStudyRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyRequest) Reset() {
	*x = GetStudyRequest{}
	mi := &file_grpc_v1_study_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyRequest) ProtoMessage() {}

func (x *GetStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyRequest.ProtoReflect.Descriptor instead.
func (*GetStudyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{2}
}

func (x *GetStudyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetStudyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyResponse) Reset() {
	*x = GetStudyResponse{}
	mi := &file_grpc_v1_study_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyResponse) ProtoMessage() {}

func (x *GetStudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyResponse.ProtoReflect.Descriptor instead.
func (*GetStudyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{3}
}

func (x *GetStudyResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetStudyResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListStudyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*GetStudyResponse    `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudyResponse) Reset() {
	*x = ListStudyResponse{}
	mi := &file_grpc_v1_study_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudyResponse) ProtoMessage() {}

func (x *ListStudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudyResponse.ProtoReflect.Descriptor instead.
func (*ListStudyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{4}
}

func (x *ListStudyResponse) GetResult() []*GetStudyResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStudyRequest) Reset() {
	*x = DeleteStudyRequest{}
	mi := &file_grpc_v1_study_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStudyRequest) ProtoMessage() {}

func (x *DeleteStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_study_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStudyRequest.ProtoReflect.Descriptor instead.
func (*DeleteStudyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_study_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteStudyRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_grpc_v1_study_proto protoreflect.FileDescriptor

const file_grpc_v1_study_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/v1/study.proto\x12\n" +
	"todoapi.v1\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x12CreateStudyRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\":\n" +
	"\x12UpdateStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"!\n" +
	"\x0fGetStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"8\n" +
	"\x10GetStudyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"I\n" +
	"\x11ListStudyResponse\x124\n" +
	"\x06result\x18\x01 \x03(\v2\x1c.todoapi.v1.GetStudyResponseR\x06result\"$\n" +
	"\x12DeleteStudyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xee\x02\n" +
	"\fStudyService\x12E\n" +
	"\vCreateStudy\x12\x1e.todoapi.v1.CreateStudyRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vUpdateStudy\x12\x1e.todoapi.v1.UpdateStudyRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\bGetStudy\x12\x1b.todoapi.v1.GetStudyRequest\x1a\x1c.todoapi.v1.GetStudyResponse\x12B\n" +
	"\tListStudy\x12\x16.google.protobuf.Empty\x1a\x1d.todoapi.v1.ListStudyResponse\x12E\n" +
	"\vDeleteStudy\x12\x1e.todoapi.v1.DeleteStudyRequest\x1a\x16.google.protobuf.EmptyB\x16Z\x14pkg/grpc/v1/todo_apib\x06proto3"

var (
	file_grpc_v1_study_proto_rawDescOnce sync.Once
	file_grpc_v1_study_proto_rawDescData []byte
)

func file_grpc_v1_study_proto_rawDescGZIP() []byte {
	file_grpc_v1_study_proto_rawDescOnce.Do(func() {
		file_grpc_v1_study_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_v1_study_proto_rawDesc), len(file_grpc_v1_study_proto_rawDesc)))
	})
	return file_grpc_v1_study_proto_rawDescData
}

var file_grpc_v1_study_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_v1_study_proto_goTypes = []any{
	(*CreateStudyRequest)(nil), // 0: todoapi.v1.CreateStudyRequest
	(*UpdateStudyRequest)(nil), // 1: todoapi.v1.UpdateStudyRequest
	(*GetStudyRequest)(nil),    // 2: todoapi.v1.GetStudyRequest
	(*GetStudyResponse)(nil),   // 3: todoapi.v1.GetStudyResponse
	(*ListStudyResponse)(nil),  // 4: todoapi.v1.ListStudyResponse
	(*DeleteStudyRequest)(nil), // 5: todoapi.v1.DeleteStudyRequest
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_grpc_v1_study_proto_depIdxs = []int32{
	3, // 0: todoapi.v1.ListStudyResponse.result:type_name -> todoapi.v1.GetStudyResponse
	0, // 1: todoapi.v1.StudyService.CreateStudy:input_type -> todoapi.v1.CreateStudyRequest
	1, // 2: todoapi.v1.StudyService.UpdateStudy:input_type -> todoapi.v1.UpdateStudyRequest
	2, // 3: todoapi.v1.StudyService.GetStudy:input_type -> todoapi.v1.GetStudyRequest
	6, // 4: todoapi.v1.StudyService.ListStudy:input_type -> google.protobuf.Empty
	5, // 5: todoapi.v1.StudyService.DeleteStudy:input_type -> todoapi.v1.DeleteStudyRequest
	6, // 6: todoapi.v1.StudyService.CreateStudy:output_type -> google.protobuf.Empty
	6, // 7: todoapi.v1.StudyService.UpdateStudy:output_type -> google.protobuf.Empty
	3, // 8: todoapi.v1.StudyService.GetStudy:output_type -> todoapi.v1.GetStudyResponse
	4, // 9: todoapi.v1.StudyService.ListStudy:output_type -> todoapi.v1.ListStudyResponse
	6, // 10: todoapi.v1.StudyService.DeleteStudy:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_v1_study_proto_init() }
func file_grpc_v1_study_proto_init() {
	if File_grpc_v1_study_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_v1_study_proto_rawDesc), len(file_grpc_v1_study_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_study_proto_goTypes,
		DependencyIndexes: file_grpc_v1_study_proto_depIdxs,
		MessageInfos:      file_grpc_v1_study_proto_msgTypes,
	}.Build()
	File_grpc_v1_study_proto = out.File
	file_grpc_v1_study_proto_goTypes = nil
	file_grpc_v1_study_proto_depIdxs = nil
}
