// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: grpc/v1/workout.proto

package todo_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkoutRequest) Reset() {
	*x = CreateWorkoutRequest{}
	mi := &file_grpc_v1_workout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkoutRequest) ProtoMessage() {}

func (x *CreateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkoutRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type UpdateWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkoutRequest) Reset() {
	*x = UpdateWorkoutRequest{}
	mi := &file_grpc_v1_workout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkoutRequest) ProtoMessage() {}

func (x *UpdateWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkoutRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkoutRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type GetWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutRequest) Reset() {
	*x = GetWorkoutRequest{}
	mi := &file_grpc_v1_workout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutRequest) ProtoMessage() {}

func (x *GetWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutRequest.ProtoReflect.Descriptor instead.
func (*GetWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkoutResponse) Reset() {
	*x = GetWorkoutResponse{}
	mi := &file_grpc_v1_workout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkoutResponse) ProtoMessage() {}

func (x *GetWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkoutResponse.ProtoReflect.Descriptor instead.
func (*GetWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkoutResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWorkoutResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ListWorkoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*GetWorkoutResponse  `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkoutResponse) Reset() {
	*x = ListWorkoutResponse{}
	mi := &file_grpc_v1_workout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkoutResponse) ProtoMessage() {}

func (x *ListWorkoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkoutResponse.ProtoReflect.Descriptor instead.
func (*ListWorkoutResponse) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkoutResponse) GetResult() []*GetWorkoutResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteWorkoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkoutRequest) Reset() {
	*x = DeleteWorkoutRequest{}
	mi := &file_grpc_v1_workout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkoutRequest) ProtoMessage() {}

func (x *DeleteWorkoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_v1_workout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkoutRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkoutRequest) Descriptor() ([]byte, []int) {
	return file_grpc_v1_workout_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWorkoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_grpc_v1_workout_proto protoreflect.FileDescriptor

const file_grpc_v1_workout_proto_rawDesc = "" +
	"\n" +
	"\x15grpc/v1/workout.proto\x12\n" +
	"todoapi.v1\x1a\x1bgoogle/protobuf/empty.proto\".\n" +
	"\x14CreateWorkoutRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\">\n" +
	"\x14UpdateWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"#\n" +
	"\x11GetWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x12GetWorkoutResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"M\n" +
	"\x13ListWorkoutResponse\x126\n" +
	"\x06result\x18\x01 \x03(\v2\x1e.todoapi.v1.GetWorkoutResponseR\x06result\"&\n" +
	"\x14DeleteWorkoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x86\x03\n" +
	"\x0eWorkoutService\x12I\n" +
	"\rCreateWorkout\x12 .todoapi.v1.CreateWorkoutRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rUpdateWorkout\x12 .todoapi.v1.UpdateWorkoutRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\n" +
	"GetWorkout\x12\x1d.todoapi.v1.GetWorkoutRequest\x1a\x1e.todoapi.v1.GetWorkoutResponse\x12F\n" +
	"\vListWorkout\x12\x16.google.protobuf.Empty\x1a\x1f.todoapi.v1.ListWorkoutResponse\x12I\n" +
	"\rDeleteWorkout\x12 .todoapi.v1.DeleteWorkoutRequest\x1a\x16.google.protobuf.EmptyB\x16Z\x14pkg/grpc/v1/todo_apib\x06proto3"

var (
	file_grpc_v1_workout_proto_rawDescOnce sync.Once
	file_grpc_v1_workout_proto_rawDescData []byte
)

func file_grpc_v1_workout_proto_rawDescGZIP() []byte {
	file_grpc_v1_workout_proto_rawDescOnce.Do(func() {
		file_grpc_v1_workout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_v1_workout_proto_rawDesc), len(file_grpc_v1_workout_proto_rawDesc)))
	})
	return file_grpc_v1_workout_proto_rawDescData
}

var file_grpc_v1_workout_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_v1_workout_proto_goTypes = []any{
	(*CreateWorkoutRequest)(nil), // 0: todoapi.v1.CreateWorkoutRequest
	(*UpdateWorkoutRequest)(nil), // 1: todoapi.v1.UpdateWorkoutRequest
	(*GetWorkoutRequest)(nil),    // 2: todoapi.v1.GetWorkoutRequest
	(*GetWorkoutResponse)(nil),   // 3: todoapi.v1.GetWorkoutResponse
	(*ListWorkoutResponse)(nil),  // 4: todoapi.v1.ListWorkoutResponse
	(*DeleteWorkoutRequest)(nil), // 5: todoapi.v1.DeleteWorkoutRequest
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_grpc_v1_workout_proto_depIdxs = []int32{
	3, // 0: todoapi.v1.ListWorkoutResponse.result:type_name -> todoapi.v1.GetWorkoutResponse
	0, // 1: todoapi.v1.WorkoutService.CreateWorkout:input_type -> todoapi.v1.CreateWorkoutRequest
	1, // 2: todoapi.v1.WorkoutService.UpdateWorkout:input_type -> todoapi.v1.UpdateWorkoutRequest
	2, // 3: todoapi.v1.WorkoutService.GetWorkout:input_type -> todoapi.v1.GetWorkoutRequest
	6, // 4: todoapi.v1.WorkoutService.ListWorkout:input_type -> google.protobuf.Empty
	5, // 5: todoapi.v1.WorkoutService.DeleteWorkout:input_type -> todoapi.v1.DeleteWorkoutRequest
	6, // 6: todoapi.v1.WorkoutService.CreateWorkout:output_type -> google.protobuf.Empty
	6, // 7: todoapi.v1.WorkoutService.UpdateWorkout:output_type -> google.protobuf.Empty
	3, // 8: todoapi.v1.WorkoutService.GetWorkout:output_type -> todoapi.v1.GetWorkoutResponse
	4, // 9: todoapi.v1.WorkoutService.ListWorkout:output_type -> todoapi.v1.ListWorkoutResponse
	6, // 10: todoapi.v1.WorkoutService.DeleteWorkout:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_v1_workout_proto_init() }
func file_grpc_v1_workout_proto_init() {
	if File_grpc_v1_workout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_v1_workout_proto_rawDesc), len(file_grpc_v1_workout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_v1_workout_proto_goTypes,
		DependencyIndexes: file_grpc_v1_workout_proto_depIdxs,
		MessageInfos:      file_grpc_v1_workout_proto_msgTypes,
	}.Build()
	File_grpc_v1_workout_proto = out.File
	file_grpc_v1_workout_proto_goTypes = nil
	file_grpc_v1_workout_proto_depIdxs = nil
}
