#build stage
FROM golang:alpine AS builder

WORKDIR /app
COPY . .

WORKDIR /app/server
RUN go get -d -v ./...

WORKDIR /app
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o ./bin/server server/cmd/.
RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/bin/server /server
COPY --from=builder /go/bin/dlv /dlv
EXPOSE 5001 4000

CMD [ "/dlv", "--listen=:4000", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/server" ]

